### PR TITLE
feat(wrap-stream-in-html): highlight connected edges

### PR DESCRIPTION
**Pull request by forivall**
## Description

Highlights connected edges to hovered node, and connected nodes to hovered edges.

## Motivation and Context

https://github.com/sverweij/dependency-cruiser/issues/343#issuecomment-670085693 you said it's on your wishlist, and i knew i could bang it out quickly. 😄 

## How Has This Been Tested?

I just launched it in the browser and hacked away. I was feeling nostalgic so it's es5.

## Screenshots

Screen Shot 2020-08-06 at 12 58 06 PM

Screen Shot 2020-08-06 at 12 58 13 PM

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation only change
- [ ] Refactor (non-breaking change which fixes an issue without changing functionality)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] :book:

  - My change doesn't require a documentation update, or ...
  - it _does_ and I have updated it

- [x] :balance_scale:
  - The contribution will be subject to [The MIT license](../LICENSE), and I'm OK with that.
  - The contribution is my own original work.
  - I am ok with the stuff in [**CONTRIBUTING.md**](./CONTRIBUTING.md).

### CODE REVIEW

**Comment by forivall** [comment]
When i update the docs, i'd also like to mention this bookmarklet i just made, so that clicking opens vscode instead of in the browser https://gist.github.com/forivall/373425de70964c8c271020cab3650048
```js
document.querySelector('svg').querySelectorAll('a').forEach(function (a) {
  var u = new URL(a.href.baseVal, document.location.href);
  u.protocol = 'vscode:';
  u.pathname = u.pathname.replace(/^\/*/, '//file/');
  a.href.baseVal = u.href;
});
```

**Comment by sverweij** [comment]
@forivall whoa - that looks nice!! I'll give it a spin tomorrow!

About the bookmarklet - that's creative! Did you consider using the [prefix](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/rules-reference.md#prefix-prefix-links-in-reports) option? I didn't know about the `vscode` protocol, but it totally works:

```javascript
  // in the options section of .dependency-cruiser.js plonk something like this:
  prefix: `vscode://file/${process.cwd()}/`,
```

```sh
# or in a command line variant for it:
depcruise -v -T dot --prefix "vscode://file/`pwd`/" -- src | dot -T svg | depcruise-wrap-stream-in-html | browser
```

That way the links in the dot (/svg) get this as a prefix. The documentation currently has an example that prefixes it with the base url of an online repository, but it's usable with other protocols as well.

**Comment by forivall** [comment]
Yeah, I just saw the prefix option earlier. Once again, you've already got something there :P

**Comment by sverweij** [comment]
@forivall thanks for this! It makes a huge difference in the usability of these reports. Nice touch to also highlight both nodes at the end of an edge on hover - and a good call to leave the existing css in place so there's a fallback for folks who disabled their javascript.

**Comment by sverweij** [comment]
(the results look too pretty not to have in the cli documentation - so I've added :-) )

**Pull request merged**
