### PR TITLE
feature: TypeScript support in Vue files (BREAKING CHANGE)

### LINKED ISSUE #515: Feature request: Vue SFC + preCompilationOnly
There is any chance to implement `preCompilationOnly` option for Vue SFC with TypeScript support?

### Context
I want to set rules with `preCompilationOnly` for my whole Vue.js + TypeScript project without being limited to `.ts` files.

### Expected Behavior

`preCompilationOnly` will include `.vue` files with TypeScript support

### Current Behavior

`preCompilationOnly` option doesn't work for Vue SFC even if it has Typescript support (via `<script lang="ts">`)

### PR DESCRIPTION
**Pull request by rklos**
## Description

An attempt to make pipeline modifications proposed by @sverweij in linked issue.

## Motivation and Context
 
Fixes #515

## How Has This Been Tested?

I did one unit test, but complexity of this project is little bit overwhelming and I don't know if I did this right enough. If not, I need some help and/or guidance to find places where I can add more tests.
Also I did some manual testing on my personal project (Vue + Typescript) where I need this feature.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation only change
- [ ] Refactor (non-breaking change which fixes an issue without changing functionality)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

Probably breaking for some users, because from now `.vue` files will report errors about pre compilation dependencies.

## Checklist

- [ ] :book:

  - My change doesn't require a documentation update, or ...
  - it _does_ and I have updated it

- [X] :balance_scale:
  - The contribution will be subject to [The MIT license](https://github.com/sverweij/dependency-cruiser/blob/develop/LICENSE), and I'm OK with that.
  - The contribution is my own original work.
  - I am ok with the stuff in [**CONTRIBUTING.md**](https://github.com/sverweij/dependency-cruiser/blob/develop/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sverweij** [comment]
hi @rklos - thanks for this pull request! I gave it a glance on Wednesday (before enabling the ci checks) and it's looking AOK. Before merging it I first want to run it locally to get a better feel, but I haven't come around to it yet (other PR's & life got in the way).

- Regarding the unit tests - as far as I can see they're correctly written and added in the right spot. It might be sufficient for 
the addition; I'll check that when I run this locally.
- I see you ticked the 'breaking change' box - could you elaborate what behavior breaks when this PR gets merged?
- Code climate complains about some duplication. You can ignore that - this PR didn't introduce that duplication (just expanded upon it) and I'm probably going to have code climate ignore the duplication anyway. I do see how to de-duplicate it but don't see how it'd make the code easier to read.
- Regarding the complexity of this project: I hear you. This is in part because of the diversity of the (Java|Type)Script world, but I'm sure this project could do better regarding maintainability. If you see some way that'd make the codebase more accessible (maintenance documentation? if so what'd be practical to get you started?) I'm all ears - after a few years I've come a bit blind in this regard.

**Comment by rklos** [comment]
I don’t know if this can be treated like a „breaking change”, but like I said in PR description - from now .vue files will report errors about pre compilation dependencies (it breaks previous behaviour when Vue is mixed with TypeScript).

Regarding the potential improvements in code readability, I'll think about it and report an issue.

**Comment by sverweij** [comment]
Hi @rklos I've checked out the PR, run it locally against a bit of vue, ran a performance non-regression test (no regression as far as that test was concerned). The solution you chose is consistent with the one chosen with the javascript/ acorn one, so that helps a lot in understandability. In other words: LGTM.

I'm afraid you're right regarding the breaking change. It'll mean major-bumping and some git admin (so it's still easy to release ^10 versions) before I can merge this PR into develop.

**Comment by rklos** [comment]
@sverweij thanks for checking this out. There is something I need to do with this PR or all further steps are on your side?

**Comment by sverweij** [comment]
hi @rklos - the steps are on my side. I b.t.w. just found a bug (in another
part of dc) - fixing that will be a breaking change as well. I intend to
release that bugfix & this PR at the same time, so there's only one major
bump. This PR will be merged as soon as GitHub is up again.

**Pull request merged**
