### PR TITLE
feature(report): adds a teamcity reporter

### LINKED ISSUE #133: Feature request: TeamCity inspection format output
For all TeamCity users, it would be cool to have a "TeamCity inspections" output, like [`eslint-teamcity`](https://github.com/andreogle/eslint-teamcity#readme) produces.

Example output (from es-lint): https://i.imgur.com/JXzBuaV.png

### Context
Better discoverability / readability of the dependency violations. Further, if the file paths are reported, TeamCity renders links to them, so you could open the files in different IDEs (for example WebStorm).

### Expected Behavior
Output dependency violations in the ["TeamCity inspections service message" format](https://www.jetbrains.com/help/teamcity/build-script-interaction-with-teamcity.html#BuildScriptInteractionwithTeamCity-ReportingInspections). (Optionally, using the `--format` CLI parameter.)

### Current Behavior
Only plain text.

### Possible Solution
Either directly implement the TC format (e.g. using [this package](https://www.npmjs.com/package/teamcity-service-messages)), or implement the `eslint` formatter contract, so that we could use [`eslint-teamcity`](https://github.com/andreogle/eslint-teamcity#readme) or other formatter plugin libraries.

### PR DESCRIPTION
**Pull request by sverweij**
## Description
Adds a new `teamcity` reporter, that emits [TeamCity service messages](https://www.jetbrains.com/help/teamcity/build-script-interaction-with-teamcity.html). 

The current approach is to emit 
- an [`inspectionType`](https://www.jetbrains.com/help/teamcity/build-script-interaction-with-teamcity.html#BuildScriptInteractionwithTeamCity-Inspectiontype
) message for each configured rule (note: maybe we should change that to _each rule violated_ as well - it depends a bit how TeamCity is using inspectionTypes without attached inspections...)
- an [`inspection`](https://www.jetbrains.com/help/teamcity/build-script-interaction-with-teamcity.html#BuildScriptInteractionwithTeamCity-Inspectioninstance) message for each rule _violated_

Use like so
```sh
depcruise --config .dependency-cruiser.json --output-type teamcity -- bin src test lib
```

Sample output: 
```
##teamcity[inspectionType id='not-to-dev-dep' name='not-to-dev-dep' description='Don|'t allow dependencies from src/app/lib to a development only package' category='dependency-cruiser' flowId='8970869134' timestamp='2019-06-02T10:37:56.812']
##teamcity[inspectionType id='no-orphans' name='no-orphans' description='Modules without any incoming or outgoing dependencies are might indicate unused code.' category='dependency-cruiser' flowId='8970869134' timestamp='2019-06-02T10:37:56.812']
##teamcity[inspectionType id='no-circular' name='no-circular' description='circular dependencies will make you dizzy' category='dependency-cruiser' flowId='8970869134' timestamp='2019-06-02T10:37:56.812']
##teamcity[inspectionType id='not-to-unresolvable' name='not-to-unresolvable' description='' category='dependency-cruiser' flowId='8970869134' timestamp='2019-06-02T10:37:56.812']
##teamcity[inspection typeId='not-to-dev-dep' message='src/asneeze.js -> node_modules/eslint/lib/api.js' file='src/asneeze.js' SEVERITY='ERROR' flowId='8970869134' timestamp='2019-06-02T10:37:56.812']
##teamcity[inspection typeId='not-to-unresolvable' message='src/index.js -> ./medontexist.json' file='src/index.js' SEVERITY='ERROR' flowId='8970869134' timestamp='2019-06-02T10:37:56.812']
##teamcity[inspection typeId='not-to-dev-dep' message='src/index.js -> node_modules/dependency-cruiser/src/main/index.js' file='src/index.js' SEVERITY='ERROR' flowId='8970869134' timestamp='2019-06-02T10:37:56.812']
##teamcity[inspection typeId='not-to-dev-dep' message='src/index.js -> node_modules/eslint/lib/api.js' file='src/index.js' SEVERITY='ERROR' flowId='8970869134' timestamp='2019-06-02T10:37:56.812']
##teamcity[inspection typeId='no-orphans' message='src/orphan.js -> src/orphan.js' file='src/orphan.js' SEVERITY='ERROR' flowId='8970869134' timestamp='2019-06-02T10:37:56.812']
```

The TeamCity format seems simple enough, but there's a bunch of hairiness involved (a.o. with the timestamp, and the escape mechanism). The reporter uses [teamcity-service-messages](https://github.com/pifantastic/teamcity-service-messages), who abstracts this away.

## Motivation and Context
fixes #133 

## How Has This Been Tested?
- [x] automated non-regression tests
- [x] new integration/ unit tests for the reporter

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] The code I add will be subject to [The MIT license](../LICENSE), and I'm OK with that.
- [x] The code I've added is my own original work.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](./CONTRIBUTING.md) document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by sverweij** [comment]
@ulrichb  Thanks for testing this at such short notice and for the detailed feedback! I really appreciate that. 

On using the low level API - it was my initial approach as well, but I ended up with the higher level API so I could keep the reporter code as simple as possible. Admittedly setting the `tsm.stdout` property to false feels slightly eerie, but it _is_ the documented way to get `teamservice-service-messages` to emit strings (a few lines before [low-level-api](https://github.com/pifantastic/teamcity-service-messages#low-level-api). I'll reconsider my reasoning and either update and document or document the decision (later maintainers will bump into it and wonder as well).

The two functional issues (_only emitting inspectionTypes_, _defaulting to `name` if there's no description_) should be fixed in dependency-cruiser@4.21.0-beta-2 - can you give it a spin again?

**Comment by ulrichb** [comment]
Hi,

I just gave it two more test runs on TeamCity and it works perfect. Many thanks!

One further (small) thing I mentioned is that the last line has no trailing `\n` (probably because of [this `.join('\n')`](https://github.com/sverweij/dependency-cruiser/pull/138/files#diff-c4d3843ca899e54b20088e8c3b158361R84)) 

=> 

image

**Comment by sverweij** [comment]
Thanks again for the amazingly fast validation. That missing trailing `\n` is a good spot - I'll fix it tomorrow!

**Comment by ulrichb** [comment]
Cool. Thanks!

One last thing I saw is that the CLI exit code is zero also in case of violations (in contrast to the "err" formatter). Is this on purpose? 

Theoretically it's okay because TeamCity handles error inspections as "failing build". On the other hand, if executing the CLI without TeamCity, the 0 exit code could be misleading.

**Comment by sverweij** [comment]
By default the reporters have 0 as an exit code to prevent script runners & build tools from erroring when they (e.g.) just generate a picture. The `err` reporter is the only exception. I can make that exception for teamcity as well if needed.

**Comment by ulrichb** [comment]
As mentioned above, when running on TeamCity it's not necessary (the build fails anyways). The advantage would be that it would be a "fail-safe" default when running the build locally (or on another CI) to return exit code > 0 when _error_ violations are reported. 

Note that the user can still override the behavior by calling `depcruise --validate ... || exit 0`. (For example I do this for `npm outdated` which always exits with 1 for any outdated package.)

Another argument would be that the [TSLint TC reporter](https://www.npmjs.com/package/tslint-teamcity-reporter) (didn't test the ESLint version) also exits > 0 for violations:

image

**Comment by ulrichb** [comment]
@sverweij Just tested the latest changes. Looks perfect. 

Thanks again for implementing this feature!

**Comment by sverweij** [comment]
wow, that was fast! 😃 

I'll release this either tonight or tomorrow by the end of the day as a regular version.

**Pull request merged**
