### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by friederbluemle**
A bunch of typo/capitalization fixes in the README/documentation files.

### CODE REVIEW

**Comment by sverweij** [comment]
Thanks for this @friederbluemle! 

That's a lot of typos you found there - did you find them by carefully reading everything or did you use automated help? If it's the latter I'd be interested to incorporate something like that into my workflow. In either case 🙇

**Comment by friederbluemle** [comment]
@sverweij Thanks for merging 👍 
I guess it was a combination of both.. I only found out about this project yesterday, so I was pretty excited to read more about it. I cloned the repo and opened it in WebStorm 2020.1 (all new 2020 versions of the JetBrains IDEs have a pretty awesome spelling/grammar checker installed by default). So that definitely helped a lot. While I was going through the documentation I occasionally did a project-wide search (&replace) to fix other occurrences of typos I encountered 😄
Really nice and useful project by the way!

**Comment by sverweij** [comment]
Thanks for you explanation @friederbluemle - and again for your PR; it's a nice improvement on the documentation (and you've spurred me on to look for a spell checker :-) )

**Comment by electrovir** [comment]
Happened to notice this conversation... I personally use [the cspell package](https://www.npmjs.com/package/cspell) (which also has a VS Code extension).

**Pull request merged**
