### PR TITLE
Use transpilers installed locally first (regardless of install location)

### PR DESCRIPTION
**Pull request by ypresto**
## Description

With this PR, dependency-cruiser will find locally installed transpilers first, then fallback to original behavior. So depcruise will work out-of-the-box with local transpilers regardless of `npx -p` or `npm i -g`.

Depends on this PR: https://github.com/sverweij/semver-try-require/pull/14

## Motivation and Context

Current depcruise will find transpilers in where depcruise itself is installed.
It means, transpilers installed in node_modules of local project are not used, unless depcruise is also installed locally.

https://github.com/sverweij/dependency-cruiser/issues/121#issuecomment-483259499
https://github.com/sverweij/dependency-cruiser/pull/661

Not only this PR solves setup issues, even we does not need to add depcruise to devDependencies. I wanted this to keep the number of dependencies fewer (e.g. for CI).

## How Has This Been Tested?

```
cd /path/to/semver-try-require # modified version
npm pack
cd /path/to/dependency-cruiser
npm i /path/to/semver-try-require/*.tgz
```

### Test for `npx`

```
cd /path/to/dependency-cruiser
rm -rf node_modules/typescript node_modules/@swc
cd /path/to/typescript-project

# ok
npx -p /path/to/dependency-cruiser depcruise -i 
npx -p ~/github/dependency-cruiser depcruise -p cli-feedback src --output-type dot --include-only "..." --ts-pre-compilation-deps
rm -rf node_modules/typescript

# ng
npx -p /path/to/dependency-cruiser depcruise -i # ng
npx -p ~/github/dependency-cruiser depcruise -p cli-feedback src --output-type dot --include-only "..." --ts-pre-compilation-deps
```

### Test for global install

```
cd /path/to/dependency-cruiser
npm pack
npm i -g dependency-cruiser-13.0.3.tgz
# we need to install locally referenced dependency manually. in my case:
npm i -g semver-try-require

cd /path/to/typescript-project

# ok
depcruise -i 
depcruise -p cli-feedback src --output-type dot --include-only "..." --ts-pre-compilation-deps


rm -rf node_modules/typescript
# ng
depcruise -i 
depcruise -p cli-feedback src --output-type dot --include-only "..." --ts-pre-compilation-deps

npm i -g typescript
# ok
depcruise -i 
depcruise -p cli-feedback src --output-type dot --include-only "..." --ts-pre-compilation-deps
```

### Of course also works when locally installed

```
cd /path/to/typescript-project
npm i -D /path/to/dependency-cruiser/dependency-cruiser-13.0.3.tgz

# ok
depcruise -i 
depcruise -p cli-feedback src --output-type dot --include-only "..." --ts-pre-compilation-deps
```

- [ ] green ci

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation only change
- [ ] Refactor (non-breaking change which fixes an issue without changing functionality)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] :book:

  - My change doesn't require a documentation update, or ...
  - it _does_ and I have updated it

- [x] :balance_scale:
  - The contribution will be subject to [The MIT license](https://github.com/sverweij/dependency-cruiser/blob/main/LICENSE), and I'm OK with that.
  - The contribution is my own original work.
  - I am ok with the stuff in [**CONTRIBUTING.md**](https://github.com/sverweij/dependency-cruiser/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ypresto** [comment]
Maybe we need --trust-foobar flag? ("Workspace Trust" in vscode)

**Comment by sverweij** [comment]
Hi @ypresto thank you for this pull request! And sorry it took such a long time to come up with a response. 

The feature you're aiming for will be useful if you don't want to install dependency-cruiser as part of a project (yet) - I like the idea! We'll have to add some caveats (the version of globally installed compilers might differ from the local ones, compilers might behave slightly differently when run globally, generally it's a good idea to keep the used compilers close to the projects), but for quickly surveying a new codebase each of these caveats can be a useful trade-off.

On the implementation: 

First off: the PR shows you've taken the time to understand the codebase _and_ put in a non-trivial amount of time into the implementation - I very much appreciate that!

- semver-try-require (which nowadays should better be called semver-try-import ...) indeed seems the right 'choke-point' to implement this. 
- In v13 dependency-cruiser was migrated to ESM as much as possible to make it work  with current features of the node platform and to future proof it - the whole ecosystem is moving in that direction as well. This pull request re-introduces commonjs in spots that were just migrated to ESM. I will consider merging this PR if we can attain the same goal, but instead with ESM.
- I do understand that in its current state additional automated tests are not yet part of the pull request. We will need them, though, before we can merge the PR. The additional tests will both help understand the added code and (once merged) will prevent non-regression.

**Comment by ypresto** [comment]
Thank you for reviewing this! :heart:

> semver-try-require indeed seems the right 'choke-point'

That's right, but its change is small that just passing a `path` argument to `createRequire()`.
https://github.com/sverweij/semver-try-require/pull/14/files#diff-31bcdc6df5f09515531a5c779db30d8281baea70f9adb2adefc07baa00b093e5R54-R57

(Off-topic):

On the other hand, there is similar but slightly different logics:

- `semver-try-require`
- `src/extract/transpile/vue-template-wrap.cjs`: with fallback module name
- `src/extract/transpile/try-import-available.mjs`: to get the version without actual import

Maybe we should move them all to the library to make sure the logic is consistent in every place.

> ESM as much as possible

Node.js has `import.meta.resolve(specifier, *parent*)` (`parent` argument seems non-standard feature) but it is behind an experimental flag and [is actively changed (v20)](https://nodejs.org/ar/blog/announcements/v20-release-announce).
So IMO it is preferable to stick with `createRequire()` until it becomes stable, leaving escape hatch to ESM.
(There is also a polyfill: https://www.npmjs.com/package/import-meta-resolve)

> additional automated tests

I'll work on this. 💪

**Comment by ypresto** [comment]
Oh no, could you reopen this please...? :pray: @sverweij

**Pull request closed without merging**
