### PR TITLE
Filter invalid symlinks

### PR DESCRIPTION
**Pull request by dword-design**
## Description

It can happen that when traversing the whole directory tree, there are invalid symlinks (that are not related to the actual dependencies in the end). This PR filters them.

## How Has This Been Tested?

I added a test that resembles this.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation only change
- [ ] Refactor (non-breaking change which fixes an issue without changing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

- [ ] :book:

  - My change doesn't require a documentation update, or ...
  - it _does_ and I have updated it

- [x] :balance_scale:
  - The contribution will be subject to [The MIT license](../LICENSE), and I'm OK with that.
  - The contribution is my own original work.
  - I am ok with the stuff in [**CONTRIBUTING.md**](./CONTRIBUTING.md).

### CODE REVIEW

**Comment by sverweij** [comment]
hi @dword-design - thanks for this fix! It looks good to be merged - could you indicate that you're OK this code will be MIT licensed (just tick the box in the PR next to the ⚖️)?

**Comment by dword-design** [comment]
@sverweij done!

**Comment by sverweij** [comment]
Thanks again @dword-design 👍 
`dependency-cruiser@9.19.1` (just published) contains your fix.

**Comment by dword-design** [comment]
@dword-design Great thanks!

**Pull request merged**
